namespace OxDAOEngine.Settings
{
    public enum DAOSetting
    {
        CurrentView,
        ShowItemInfo,
        CategoryPanelPinned,
        CategoryPanelExpanded,
        ItemInfoPosition,
        ItemInfoPanelPinned,
        ItemInfoPanelExpanded,
        QuickFilterPinned,
        QuickFilterExpanded,
        ShowCategories,
        AlwaysExpandedCategories,
        HideEmptyCategory,
        ShowCards,
        CardsPageSize,
        CardsAllowExpand,
        CardsAllowEdit,
        CardsAllowDelete,
        ShowIcons,
        IconsSize,
        IconMapping,
        IconsPageSize,
        IconClickVariant,
        ShowQuickFilter,
        QuickFilterTextFieldOperation
    }
}
